/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness/readiness probe with Postgres connectivity check.
         * @description Probe Postgres and return the canonical health envelope.
         *
         *     The handler intentionally returns :class:`fastapi.responses.JSONResponse`
         *     rather than the Pydantic model directly so the failure branch can
         *     set the 503 status code without raising an exception (which would
         *     route through the RFC 7807 catch-all in
         *     :mod:`matchlayer_api.core.errors` and produce the wrong response
         *     shape for a healthcheck).
         *
         *     Args:
         *         session: Request-scoped async SQLAlchemy session, yielded by
         *             :func:`~matchlayer_api.core.db.get_session`. Tests override
         *             this dependency via FastAPI's ``app.dependency_overrides``
         *             mapping (task 3.11).
         *
         *     Returns:
         *         :class:`JSONResponse` with status 200 and body ``{"status": "ok"}``
         *         when the ``SELECT 1`` probe succeeds; status 503 and body
         *         ``{"status": "unhealthy", "reason": "database_unreachable"}``
         *         when SQLAlchemy raises any subclass of :class:`SQLAlchemyError`.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Request */
        post: operations["password_reset_request_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Confirm */
        post: operations["password_reset_confirm_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Resumes
         * @description List the caller's non-deleted resumes (cursor-paginated).
         *
         *     ``limit`` is constrained to ``1..100`` by :class:`~fastapi.Query`; an
         *     out-of-range or non-numeric value raises FastAPI's
         *     ``RequestValidationError``, which the foundation handler renders as the
         *     422 ``validation_error`` envelope (Requirement 4.3). Results are scoped
         *     to the caller, ordered ``created_at`` descending, and projected onto the
         *     safe :class:`ResumeResponse` shape -- no ``extracted_text`` or
         *     ``storage_key`` (Requirements 4.1, 4.2).
         *
         *     Args:
         *         user: The authenticated owner.
         *         session: The request-scoped session (read-only path, no commit).
         *         settings: Active settings.
         *         limit: Page size, ``1..100`` (default 20).
         *         cursor: Opaque cursor from a prior page, or ``None`` for the first.
         *
         *     Returns:
         *         A :class:`ResumeListResponse` page plus the next cursor.
         */
        get: operations["list_resumes_api_v1_resumes_get"];
        put?: never;
        /**
         * Create Resume
         * @description Upload one resume; 201 with the safe field set.
         *
         *     Pre-service guards run in the order the design's upload sequence
         *     prescribes -- the per-user rate limit (dependency) and the 413
         *     declared-length check both short-circuit before any object is written
         *     (Requirement 2.2) -- followed by idempotency replay, then the service
         *     orchestration (quota -> MIME -> zip-bomb -> store -> insert -> extract
         *     -> audit).
         *
         *     On a quota breach the service stages a ``quota_rejected`` audit row and
         *     raises :class:`QuotaExceededError`; this handler commits that row before
         *     re-raising so the audit lands even though the 429 short-circuits the
         *     upload (Requirement 11.6). On success the ``resumes`` row and the
         *     ``resume_uploaded`` audit row commit together (Requirement 2.7), and the
         *     response carries only the safe field set -- never ``extracted_text``,
         *     ``storage_key``, or the raw bytes (Requirement 2.9).
         *
         *     Args:
         *         request: The active request (used for the ``Content-Length``
         *             fallback in the 413 guard).
         *         file: The multipart ``file`` part (Requirement 2.1).
         *         user: The authenticated owner.
         *         session: The request-scoped session (this handler owns the commit).
         *         settings: Active settings (the ``resume_max_bytes`` ceiling).
         *         idempotency_store: Redis-backed store for idempotent replay.
         *         idempotency_key: Optional ``Idempotency-Key`` header (Requirement
         *             2.8).
         *
         *     Returns:
         *         The created (or replayed) :class:`ResumeResponse`.
         *
         *     Raises:
         *         PayloadTooLargeError: Declared length over ``MATCHLAYER_RESUME_MAX_BYTES``
         *             (413 ``payload_too_large``).
         *         QuotaExceededError: Daily Upload_Quota reached (429 ``quota_exceeded``).
         */
        post: operations["create_resume_api_v1_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resume
         * @description Return a single owned, non-deleted resume, or 404.
         *
         *     The service collapses a missing row, a soft-deleted row, and a row
         *     owned by another User_Account into the same
         *     :class:`~matchlayer_api.core.errors.NotFoundError` (404 ``not_found``),
         *     so the existence of another account's resource is never disclosed
         *     (Requirements 1.5, 1.6, 4.4).
         *
         *     Args:
         *         resume_id: The resume id from the path.
         *         user: The authenticated owner.
         *         session: The request-scoped session (read-only path, no commit).
         *         settings: Active settings.
         *
         *     Returns:
         *         The owned :class:`ResumeResponse`.
         */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Resume
         * @description Soft-delete the caller's resume; 204, idempotent.
         *
         *     Delegates to the idempotent
         *     :meth:`~matchlayer_api.services.resumes.Resume_Service.soft_delete_resume`:
         *     an active owned row is stamped ``deleted_at`` and emits one
         *     ``resume_deleted`` audit row (Requirement 4.5); an already-soft-deleted
         *     owned row is a no-op with no second audit row (Requirement 4.6); a
         *     missing or other-owner id raises
         *     :class:`~matchlayer_api.core.errors.NotFoundError` (404, no disclosure).
         *     The commit persists ``deleted_at`` and the audit row together; on the
         *     no-op and 404 paths there is nothing staged to commit.
         *
         *     Args:
         *         resume_id: The resume id from the path.
         *         user: The authenticated owner.
         *         session: The request-scoped session (this handler owns the commit).
         *         settings: Active settings.
         */
        delete: operations["delete_resume_api_v1_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Return one cursor-paginated page of the caller's non-deleted matches.
         *
         *     Ordered by ``created_at`` descending (ties broken by ``id`` descending),
         *     scoped to the requesting user (Requirements 1.4, 9.1). ``limit`` outside
         *     1..100 fails query validation → 422 ``validation_error``. Each item is a
         *     :class:`MatchListItem`, which omits ``job_description_text`` (Requirement
         *     9.2). ``next_cursor`` is ``None`` on the last page.
         */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        /**
         * Create Match
         * @description Score a resume against a job description and persist the Match_Result.
         *
         *     The request body is validated by :class:`CreateMatchRequest`, whose
         *     ``job_description`` field validator enforces the trimmed-length window
         *     ``MATCHLAYER_JD_MIN_CHARS``..``MATCHLAYER_JD_MAX_CHARS`` — a violation (or
         *     any other Pydantic failure) surfaces as 422 ``validation_error`` before this
         *     handler runs (Requirements 8.2, 8.3).
         *
         *     Idempotency (Requirement 8.9): when an ``Idempotency-Key`` header matches a
         *     record stored for this user within the preceding 24h, the original 201
         *     response is replayed without creating a second Match_Result. Otherwise the
         *     service creates the match, the router commits, and the response is stored
         *     under the key for future replays.
         *
         *     Failure mapping:
         *       * ``resume_id`` that is malformed, or does not resolve to an owned,
         *         non-deleted resume → 404 ``not_found`` (Requirement 8.4; no disclosure).
         *       * referenced resume whose ``extraction_status != 'succeeded'`` → 422
         *         ``resume_not_extractable`` (Requirement 8.5).
         *       * daily Scoring_Quota reached → 429 ``quota_exceeded``; the service stages
         *         a ``quota_rejected`` audit row which this handler commits before the
         *         error propagates (Requirement 11.6 audit; the ``detail`` + ``Retry-After``
         *         are owned by the service/dependency layer).
         */
        post: operations["create_match_api_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match
         * @description Return one owned, non-deleted Match_Result.
         *
         *     A missing, soft-deleted, or other-owner match (or a malformed id) yields the
         *     ``not_found`` envelope, so another account's match is indistinguishable from
         *     one that does not exist (Requirements 1.5, 1.6, 9.3). The match is returned
         *     even when its referenced resume was later soft-deleted — the score and
         *     analysis are retained independently of the resume's lifecycle (Requirement
         *     9.6, guaranteed by the service's query, which does not filter on the
         *     resume's ``deleted_at``).
         */
        get: operations["get_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Match
         * @description Soft-delete an owned Match_Result; idempotent (Requirements 9.4, 9.5).
         *
         *     On the first delete of an owned, non-deleted match the service sets
         *     ``deleted_at`` and stages a ``match_deleted`` audit row; the router commits
         *     so both land together. A match that is already soft-deleted, does not exist,
         *     is owned by another user, or carries a malformed id is a silent no-op that
         *     emits no second audit row — every case returns 204 uniformly, disclosing
         *     nothing about another account's data (Requirements 1.4, 9.5).
         */
        delete: operations["delete_match_api_v1_matches__match_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/coaching-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Coaching Reports
         * @description One newest-first page of the match's Coaching_Reports (Req 16.4).
         */
        get: operations["list_coaching_reports_api_v1_matches__match_id__coaching_reports_get"];
        put?: never;
        /**
         * Create Coaching Report
         * @description Generate (or reuse) a Coaching_Report for an owned match (Req 5.1).
         *
         *     Runs the shared pipeline with the Resume_Coach spec: persisted-result
         *     reuse under the same active prompt version + model serves the stored
         *     report with no provider call and no quota consumption (Req 5.4); any
         *     LLM failure lands on the locally-derived fallback with 200 (Req 5.5,
         *     9.1). ``stream=true`` delivers the same outcome over SSE (Req 11.1).
         */
        post: operations["create_coaching_report_api_v1_matches__match_id__coaching_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/coaching-reports/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coaching Report
         * @description One persisted Coaching_Report by id (Req 16.3, 16.9).
         */
        get: operations["get_coaching_report_api_v1_matches__match_id__coaching_reports__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/bullet-rewrites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bullet Rewrites
         * @description One newest-first page of the match's Bullet_Rewrites (Req 16.4).
         */
        get: operations["list_bullet_rewrites_api_v1_matches__match_id__bullet_rewrites_get"];
        put?: never;
        /**
         * Create Bullet Rewrite
         * @description Rewrite the submitted bullets against an owned match (Req 6.1).
         *
         *     ``BulletRewriteRequest`` validation (count 1..``llm_max_bullets``, no
         *     empty/whitespace bullet, each ≤ ``llm_max_bullet_chars``) runs before
         *     this handler; a violation is a 422 RFC 7807 response before any
         *     redaction, quota accounting, or LLM work — and before any stream
         *     opens (Req 6.3, 11.4). Bullets are Restricted PII and travel only
         *     into the pipeline, which redacts them. ``stream=true`` delivers the
         *     outcome over SSE (Req 11.1).
         */
        post: operations["create_bullet_rewrite_api_v1_matches__match_id__bullet_rewrites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/bullet-rewrites/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bullet Rewrite
         * @description One persisted Bullet_Rewrite by id (Req 6.5, 16.3, 16.9).
         */
        get: operations["get_bullet_rewrite_api_v1_matches__match_id__bullet_rewrites__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/interview-question-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interview Question Sets
         * @description One newest-first page of the match's Interview_Question_Sets (Req 16.4).
         */
        get: operations["list_interview_question_sets_api_v1_matches__match_id__interview_question_sets_get"];
        put?: never;
        /**
         * Create Interview Question Set
         * @description Generate an Interview_Question_Set for an owned match (Req 7.1).
         *
         *     ``stream=true`` delivers the outcome over SSE (Req 11.1).
         */
        post: operations["create_interview_question_set_api_v1_matches__match_id__interview_question_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/interview-question-sets/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interview Question Set
         * @description One persisted Interview_Question_Set by id (Req 7.4, 16.3, 16.9).
         */
        get: operations["get_interview_question_set_api_v1_matches__match_id__interview_question_sets__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/last-reset-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last Reset Link */
        get: operations["last_reset_link_api_v1_dev_last_reset_link_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_resume_api_v1_resumes_post */
        Body_create_resume_api_v1_resumes_post: {
            /**
             * File
             * @description The resume file (PDF or DOCX).
             */
            file: string;
        };
        /**
         * BulletRewrite
         * @description The Bullet_Rewriter structured output (Requirement 6.2).
         *
         *     Exactly one entry per submitted bullet, in submission order. The
         *     count/order/original-text alignment against the actual submission is
         *     enforced by the feature service (Requirement 6.7) because the
         *     submitted bullets are request state this schema cannot see; the
         *     schema itself guarantees at least one entry and each entry's bounds.
         */
        BulletRewrite: {
            /**
             * Entries
             * @description One entry per submitted bullet, in submission order.
             */
            entries: components["schemas"]["BulletRewriteEntry"][];
        };
        /**
         * BulletRewriteEntry
         * @description One submitted bullet paired with its rewritten alternatives.
         *
         *     ``original`` must byte-for-byte match a submitted bullet text — the
         *     post-validation alignment check in the Bullet_Rewriter feature
         *     service compares it exactly (Requirement 6.7), so no whitespace
         *     normalization is applied here.
         */
        BulletRewriteEntry: {
            /**
             * Original
             * @description The submitted bullet text, exactly as submitted.
             */
            original: string;
            /**
             * Alternatives
             * @description 1 to 3 rewritten alternatives targeting the job description.
             */
            alternatives: string[];
            /**
             * Rationale
             * @description Non-empty explanation of how the rewrite better targets the job description.
             */
            rationale: string;
        };
        /**
         * BulletRewriteListResponse
         * @description One newest-first page of a match's persisted Bullet_Rewrites.
         */
        BulletRewriteListResponse: {
            /**
             * Items
             * @description Persisted Bullet_Rewrites in descending created_at order.
             */
            items: components["schemas"]["LLMResultEnvelope_BulletRewrite_"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null on the last page. Clients pass it back unmodified.
             */
            next_cursor?: string | null;
        };
        /**
         * BulletRewriteRequest
         * @description Body of ``POST /api/v1/matches/{matchId}/bullet-rewrites`` (Req 6.3).
         *
         *     Validation failures surface as FastAPI's 422 RFC 7807 response before
         *     the router touches the orchestrator, so no redaction, quota, cache, or
         *     LLM_Provider work happens for an invalid submission. Bullet text is
         *     accepted exactly as submitted — no stripping — because the
         *     Requirement 6.7 alignment check compares ``original`` byte-for-byte
         *     against the submitted text.
         *
         *     The count ceiling and per-bullet length ceiling are configuration
         *     (``MATCHLAYER_LLM_MAX_BULLETS`` / ``MATCHLAYER_LLM_MAX_BULLET_CHARS``)
         *     and therefore checked by the validator below at validation time,
         *     mirroring the settings-reading validator precedent in
         *     ``services/llm/schemas.py`` (InterviewQuestionSet's ceiling).
         */
        BulletRewriteRequest: {
            /**
             * Bullets
             * @description 1 to MATCHLAYER_LLM_MAX_BULLETS resume bullet texts to rewrite, in the order they should be rewritten. None may be empty or whitespace-only; each is at most MATCHLAYER_LLM_MAX_BULLET_CHARS characters.
             */
            bullets: string[];
        };
        /**
         * CoachingReport
         * @description The Resume_Coach structured output (Requirement 5.2).
         *
         *     Overall feedback on a resume against a specific job description:
         *     a summary, strengths, gaps, and 3..10 prioritized improvement
         *     actions ordered from highest to lowest priority. A response
         *     violating the bounds or the ordering fails schema validation and
         *     takes the Fallback_Response path (Requirement 8.3).
         */
        CoachingReport: {
            /**
             * Summary
             * @description Overall summary of how the resume matches the job description.
             */
            summary: string;
            /**
             * Strengths
             * @description Strengths of the resume relative to the job description.
             */
            strengths: string[];
            /**
             * Gaps
             * @description Gaps or weaknesses of the resume relative to the job description.
             */
            gaps: string[];
            /**
             * Improvements
             * @description 3 to 10 concrete improvement actions, ordered from highest priority (rank 1) to lowest priority.
             */
            improvements: components["schemas"]["ImprovementAction"][];
        };
        /**
         * CoachingReportListResponse
         * @description One newest-first page of a match's persisted Coaching_Reports.
         */
        CoachingReportListResponse: {
            /**
             * Items
             * @description Persisted Coaching_Reports in descending created_at order.
             */
            items: components["schemas"]["LLMResultEnvelope_CoachingReport_"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null on the last page. Clients pass it back unmodified.
             */
            next_cursor?: string | null;
        };
        /**
         * CreateMatchRequest
         * @description Body of ``POST /api/v1/matches`` (Requirement 8.1).
         *
         *     Fields:
         *       * ``resume_id`` -- the string UUIDv7 of one of the caller's resumes.
         *         Ownership / existence / extractability are resolved server-side by
         *         the Scoring_Service (404 ``not_found`` for a missing, deleted, or
         *         other-owner resume per Requirement 8.4; 422 ``resume_not_extractable``
         *         when the resume's ``extraction_status`` is not ``succeeded`` per
         *         Requirement 8.5). The schema validates only that a non-empty string
         *         was supplied.
         *       * ``job_description`` -- the pasted job-description text. A baseline
         *         ``min_length=1`` floor protects FastAPI's request parser from an
         *         empty string; the real window is enforced by
         *         :meth:`_check_job_description_length`, which trims and checks the
         *         length against ``MATCHLAYER_JD_MIN_CHARS``..``MATCHLAYER_JD_MAX_CHARS``
         *         (Requirement 8.3). A violation raises ``ValueError``, which Pydantic
         *         surfaces as a 422 ``validation_error`` through the foundation RFC
         *         7807 handler (Requirement 8.2).
         */
        CreateMatchRequest: {
            /**
             * Resume Id
             * @description UUIDv7 (string) of the resume to score. Ownership and extractability are resolved server-side; the schema only checks that a non-empty string was supplied.
             */
            resume_id: string;
            /**
             * Job Description
             * @description Pasted job-description text. The trimmed length must fall within MATCHLAYER_JD_MIN_CHARS..MATCHLAYER_JD_MAX_CHARS (defaults 30..50000); a violation returns 422 validation_error.
             */
            job_description: string;
        };
        /**
         * FailureReason
         * @description Closed set of LLM failure categories (Requirement 9.2).
         *
         *     Every fallback-producing failure in the pipeline maps to exactly one
         *     of these values (design §"Orchestrator" failure taxonomy). The same
         *     values are recorded as ``llm_invocation_logs.failure_category`` and
         *     exposed to the frontend via :class:`LLMResultEnvelope.fallback_reason`
         *     so the Web_App can label degraded content honestly (Requirement 17.4).
         * @enum {string}
         */
        FailureReason: "provider_error" | "timeout" | "schema_validation_failed" | "redaction_failed" | "prompt_template_missing" | "quota_accounting_unavailable" | "llm_unavailable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Body returned on the success path: ``{"status": "ok"}``.
         *
         *     Typed with :class:`typing.Literal` so the generated OpenAPI schema
         *     pins the response to that exact shape, which in turn produces a
         *     precise type when :mod:`packages/shared-types` re-exports it as
         *     ``HealthResponse`` (task 5.4).
         */
        HealthResponse: {
            /**
             * Status
             * @description Liveness signal. Always the literal string 'ok' on a 200 response.
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Semantic Scoring
             * @description Phase 2 semantic-pipeline availability (Requirement 7.5). 'available' when the Embedding_Model + spaCy pipeline loaded at startup; 'unavailable' in Degraded_Mode. Exactly these two machine-readable values — a degraded instance still returns 200 so orchestration never restart-loops it; operators detect Degraded_Mode from this field without reading logs.
             * @enum {string}
             */
            semantic_scoring: "available" | "unavailable";
            /**
             * Llm
             * @description Phase 3 LLM-subsystem availability (Requirement 10.1). 'unavailable' iff the provider API key was absent at startup or the Spend_Circuit_Breaker is open (LLM_Unavailable, Requirement 10.2); 'available' otherwise (Requirement 10.6). Exactly these two machine-readable values — the field never changes the HTTP status code and never exposes the API key, spend figures, or provider account details (Requirement 10.5).
             * @enum {string}
             */
            llm: "available" | "unavailable";
        };
        /**
         * HealthUnhealthyResponse
         * @description Body returned on the failure path.
         *
         *     Surfaced in the OpenAPI ``responses`` map for ``503`` so the
         *     contract is explicit: the response carries a short symbolic
         *     ``reason`` token and never a DSN, credentials, or any PII.
         */
        HealthUnhealthyResponse: {
            /**
             * Status
             * @description Liveness signal. Always the literal string 'unhealthy' on a 503 response.
             * @default unhealthy
             * @constant
             */
            status: "unhealthy";
            /**
             * Reason
             * @description Symbolic, machine-readable failure code. Phase 6 load balancers and alerting branch on this token; it never contains DSN, credentials, or PII.
             * @constant
             */
            reason: "database_unreachable";
        };
        /**
         * ImprovementAction
         * @description One concrete improvement action with its explicit priority rank.
         *
         *     ``priority`` is a rank: 1 is the highest-priority action, larger
         *     values are progressively lower priority (Requirement 5.2 — "each
         *     action carries an explicit priority rank").
         */
        ImprovementAction: {
            /**
             * Priority
             * @description Explicit priority rank: 1 is the highest-priority action; larger values are lower priority.
             */
            priority: number;
            /**
             * Action
             * @description Concrete, user-actionable improvement instruction.
             */
            action: string;
        };
        /**
         * InterviewQuestion
         * @description One likely interview question (Requirement 7.2).
         */
        InterviewQuestion: {
            /**
             * Question
             * @description The question text: non-empty, at most 300 characters.
             */
            question: string;
            /** @description Exactly one of 'technical', 'behavioral', or 'experience-gap'. */
            category: components["schemas"]["InterviewQuestionCategory"];
            /**
             * Reason
             * @description Non-empty grounding (at most 500 characters) for why this resume + job-description pair makes the question likely.
             */
            reason: string;
        };
        /**
         * InterviewQuestionCategory
         * @description Closed category set for interview questions (Requirement 7.2).
         * @enum {string}
         */
        InterviewQuestionCategory: "technical" | "behavioral" | "experience-gap";
        /**
         * InterviewQuestionSet
         * @description The Interview_Question_Generator structured output (Requirement 7.3).
         *
         *     Between 5 and ``MATCHLAYER_LLM_MAX_QUESTIONS`` (default 15) questions.
         *     An out-of-bounds count is a validation failure — never truncated or
         *     padded (Requirement 7.7). The floor is a schema constant; the ceiling
         *     is read from settings by the validator below (design: "5..
         *     llm_max_questions (validator reads settings)"), mirroring the
         *     settings-reading validator precedent in ``api/matches/schemas.py``.
         *     Startup validation guarantees the ceiling is >= the floor
         *     (Requirement 7.8).
         */
        InterviewQuestionSet: {
            /**
             * Questions
             * @description 5 to MATCHLAYER_LLM_MAX_QUESTIONS likely interview questions.
             */
            questions: components["schemas"]["InterviewQuestion"][];
        };
        /**
         * InterviewQuestionSetListResponse
         * @description One newest-first page of a match's persisted Interview_Question_Sets.
         */
        InterviewQuestionSetListResponse: {
            /**
             * Items
             * @description Persisted Interview_Question_Sets in descending created_at order.
             */
            items: components["schemas"]["LLMResultEnvelope_InterviewQuestionSet_"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null on the last page. Clients pass it back unmodified.
             */
            next_cursor?: string | null;
        };
        /**
         * KeywordOut
         * @description One analyzed keyword and its weight (``{term, weight}``).
         *
         *     Mirrors the scorer's ``Keyword`` dataclass and the
         *     ``match_results.matched_keywords`` / ``missing_keywords`` JSONB shape.
         *     Lists of these are returned ordered by descending weight so the most
         *     important terms appear first (Requirement 6.6).
         *
         *     ``from_attributes=True`` lets the router validate this either from the
         *     JSONB list-of-dicts loaded off the ORM row or from the scorer's
         *     ``Keyword`` dataclass attributes, without renaming.
         */
        KeywordOut: {
            /**
             * Term
             * @description Normalized keyword term (case-folded; lexicon-canonical for known skills).
             */
            term: string;
            /**
             * Weight
             * @description Relative importance of the term (lexicon weight for a known skill, otherwise the term's TF-IDF score).
             */
            weight: number;
        };
        /** LLMResultEnvelope[BulletRewrite] */
        LLMResultEnvelope_BulletRewrite_: {
            /**
             * Id
             * @description UUIDv7 (string) of the persisted LLM_Result; null for fallbacks, which are never persisted.
             */
            id?: string | null;
            /**
             * Is Fallback
             * @description True when the result is a Fallback_Response built without the LLM; false for validated LLM output.
             */
            is_fallback: boolean;
            /** @description The failure category that triggered the fallback; null for LLM-produced results. */
            fallback_reason?: components["schemas"]["FailureReason"] | null;
            /**
             * Prompt Template Version
             * @description The active Prompt_Template version the result was produced under; null for fallbacks.
             */
            prompt_template_version?: number | null;
            /**
             * Created At
             * @description Persistence timestamp (timezone-aware) of the LLM_Result; null for fallbacks.
             */
            created_at?: string | null;
            /** @description The feature payload (CoachingReport, BulletRewrite, or InterviewQuestionSet). Fallback content conforms to the same schema. */
            result: components["schemas"]["BulletRewrite"];
        };
        /** LLMResultEnvelope[CoachingReport] */
        LLMResultEnvelope_CoachingReport_: {
            /**
             * Id
             * @description UUIDv7 (string) of the persisted LLM_Result; null for fallbacks, which are never persisted.
             */
            id?: string | null;
            /**
             * Is Fallback
             * @description True when the result is a Fallback_Response built without the LLM; false for validated LLM output.
             */
            is_fallback: boolean;
            /** @description The failure category that triggered the fallback; null for LLM-produced results. */
            fallback_reason?: components["schemas"]["FailureReason"] | null;
            /**
             * Prompt Template Version
             * @description The active Prompt_Template version the result was produced under; null for fallbacks.
             */
            prompt_template_version?: number | null;
            /**
             * Created At
             * @description Persistence timestamp (timezone-aware) of the LLM_Result; null for fallbacks.
             */
            created_at?: string | null;
            /** @description The feature payload (CoachingReport, BulletRewrite, or InterviewQuestionSet). Fallback content conforms to the same schema. */
            result: components["schemas"]["CoachingReport"];
        };
        /** LLMResultEnvelope[InterviewQuestionSet] */
        LLMResultEnvelope_InterviewQuestionSet_: {
            /**
             * Id
             * @description UUIDv7 (string) of the persisted LLM_Result; null for fallbacks, which are never persisted.
             */
            id?: string | null;
            /**
             * Is Fallback
             * @description True when the result is a Fallback_Response built without the LLM; false for validated LLM output.
             */
            is_fallback: boolean;
            /** @description The failure category that triggered the fallback; null for LLM-produced results. */
            fallback_reason?: components["schemas"]["FailureReason"] | null;
            /**
             * Prompt Template Version
             * @description The active Prompt_Template version the result was produced under; null for fallbacks.
             */
            prompt_template_version?: number | null;
            /**
             * Created At
             * @description Persistence timestamp (timezone-aware) of the LLM_Result; null for fallbacks.
             */
            created_at?: string | null;
            /** @description The feature payload (CoachingReport, BulletRewrite, or InterviewQuestionSet). Fallback content conforms to the same schema. */
            result: components["schemas"]["InterviewQuestionSet"];
        };
        /**
         * LastResetLinkResponse
         * @description Body of ``GET /api/v1/dev/last-reset-link`` (dev-only).
         *
         *     Returns the most recently generated password-reset link, or both
         *     fields ``null`` when the in-process store is empty (Requirement
         *     13.3, Dev-Mode Reset-Link Surface §12.1). The router that exposes
         *     this endpoint is only mounted onto the FastAPI app when
         *     ``MATCHLAYER_ENVIRONMENT=development``; in any other environment
         *     the path returns the foundation 404 envelope (Requirement 13.4).
         */
        LastResetLinkResponse: {
            /**
             * Link
             * @description Plaintext reset link including the single-use token, or null when no reset has been requested since the API process started.
             */
            link?: string | null;
            /**
             * Created At
             * @description When the link was recorded, or null when the store is empty.
             */
            created_at?: string | null;
        };
        /**
         * LoginRequest
         * @description Body of ``POST /api/v1/auth/login`` (Requirement 2.1).
         *
         *     The login schema deliberately does **not** enforce the registration
         *     minimum-length floor on the supplied password: doing so would be an
         *     enumeration vector -- ``"a"`` would 422 instantly while a 12-char
         *     wrong password would burn the dummy-Argon2id-verify path (§8.3).
         *     The schema only checks that the field is non-empty so FastAPI's
         *     request parser doesn't dispatch to the service with an empty string.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             * @description RFC 5321-compliant email address.
             */
            email: string;
            /**
             * Password
             * @description Plaintext password. No upper-floor length enforcement here -- the dummy-hash timing equalizer in Auth_Service relies on every non-empty input reaching the verify step (Password Handling §8.3).
             */
            password: string;
        };
        /**
         * MatchListItem
         * @description Trimmed Match_Result projection for the list view (Requirement 9.2).
         *
         *     Carries the minimum fields Requirement 9.2 enumerates: ``id``,
         *     ``resume_id``, ``score``, and ``created_at``. ``job_description_text``
         *     is **omitted** (Restricted PII; the list never carries it), as are the
         *     heavier JSONB columns (breakdown, keywords, suggestions) which belong on
         *     the single-match detail view rather than every list row.
         *
         *     ``from_attributes=True`` lets the router build each item from the
         *     SQLAlchemy ``MatchResult`` row; the unlisted columns are simply never
         *     read.
         */
        MatchListItem: {
            /**
             * Id
             * @description UUIDv7 of the Match_Result, encoded as a string.
             */
            id: string;
            /**
             * Resume Id
             * @description UUIDv7 (string) of the resume that was scored.
             */
            resume_id: string;
            /**
             * Score
             * @description The final match score, an integer in [0, 100].
             */
            score: number;
            /**
             * Created At
             * Format: date-time
             * @description Scoring timestamp (timezone-aware).
             */
            created_at: string;
        };
        /**
         * MatchListResponse
         * @description Body of ``GET /api/v1/matches`` (Requirement 9.1).
         *
         *     A single page of the requesting User_Account's non-deleted
         *     Match_Results, ordered by ``created_at`` descending, plus an opaque
         *     ``next_cursor`` for cursor-based pagination per ``conventions.md``
         *     "Pagination" (offset pagination is explicitly avoided). ``next_cursor``
         *     is an opaque token the client echoes back via the ``cursor`` query
         *     parameter to fetch the following page; it is ``None`` when there are no
         *     further pages.
         *
         *     Each item is a :class:`MatchListItem`, so no row in the list carries
         *     ``job_description_text`` (Requirement 9.2).
         */
        MatchListResponse: {
            /**
             * Items
             * @description The matches on this page, ordered by created_at descending.
             */
            items: components["schemas"]["MatchListItem"][];
            /**
             * Next Cursor
             * @description Opaque pagination cursor for the next page, or null when this is the last page. Echo back via the ?cursor= query parameter.
             */
            next_cursor?: string | null;
        };
        /**
         * MatchResponse
         * @description Full Match_Result projection (Requirement 8.7).
         *
         *     Carries **exactly** the ten fields Requirement 8.7 enumerates: ``id``,
         *     ``resume_id``, ``score``, ``score_breakdown``, ``matched_keywords``,
         *     ``missing_keywords``, ``suggestions``, ``scorer_version``,
         *     ``created_at``, and ``updated_at``. Returned by ``POST /api/v1/matches``
         *     (201) and ``GET /api/v1/matches/{id}`` (Requirement 9.3).
         *
         *     ``job_description_text`` is intentionally absent. It is Restricted PII
         *     per ``security.md`` "Data classification" and the design deliberately
         *     keeps it out of every match response body (Requirement 8.8); this
         *     exclusion is a security control, not a convenience.
         *
         *     ``from_attributes=True`` lets the router build a response directly from
         *     the SQLAlchemy ``MatchResult`` row via
         *     ``MatchResponse.model_validate(match)``. The JSONB columns
         *     (``score_breakdown`` as a dict, ``matched_keywords`` /
         *     ``missing_keywords`` / ``suggestions`` as lists of dicts) validate
         *     against the nested models above, and the excluded ``job_description_text``
         *     column is simply never read.
         */
        MatchResponse: {
            /**
             * Id
             * @description UUIDv7 of the Match_Result, encoded as a string.
             */
            id: string;
            /**
             * Resume Id
             * @description UUIDv7 (string) of the resume that was scored.
             */
            resume_id: string;
            /**
             * Score
             * @description The final match score, an integer in [0, 100].
             */
            score: number;
            /** @description The explainable component/weight breakdown behind the score. */
            score_breakdown: components["schemas"]["ScoreBreakdownOut"];
            /**
             * Matched Keywords
             * @description Analyzed keywords present in the resume, ordered by descending weight.
             */
            matched_keywords: components["schemas"]["KeywordOut"][];
            /**
             * Missing Keywords
             * @description Analyzed keywords absent from the resume, ordered by descending weight.
             */
            missing_keywords: components["schemas"]["KeywordOut"][];
            /**
             * Suggestions
             * @description Rule-based improvement suggestions, ordered by descending missing-keyword weight.
             */
            suggestions: components["schemas"]["SuggestionOut"][];
            /**
             * Scorer Version
             * @description The Scorer_Version (algorithm + lexicon version) the score was produced under, making the stored score reproducible.
             */
            scorer_version: string;
            /**
             * Created At
             * Format: date-time
             * @description Scoring timestamp (timezone-aware).
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last-modified timestamp (timezone-aware).
             */
            updated_at: string;
        };
        /**
         * MePatchRequest
         * @description Body of ``PATCH /api/v1/auth/me`` (Requirement 6.5).
         *
         *     Per Requirement 6.5 ``display_name`` is the "optional field"; this
         *     is what makes the endpoint forward-compatible -- adding a second
         *     optional field in a later spec is a non-breaking change. In
         *     Phase 1 the only writable column is ``display_name``, so a request
         *     with no fields set is a no-op (returns 200 with the unchanged
         *     user); Auth_Service only emits the ``display_name_changed`` audit
         *     event when the field is actually present.
         */
        MePatchRequest: {
            /**
             * Display Name
             * @description New display name. When present, validated per Requirement 6.6: non-empty after strip, <=64 chars after strip, characters limited to Unicode classes L, M, N, Pd, Pc, Zs.
             */
            display_name?: string | null;
        };
        /**
         * MeResponse
         * @description Body of ``GET /api/v1/auth/me`` and ``PATCH /api/v1/auth/me``.
         *
         *     Identical field set to :class:`UserResponse` -- the redundancy is
         *     deliberate. Declaring a distinct class produces a distinct OpenAPI
         *     schema name, so the curated frontend re-export
         *     ``packages/shared-types/src/index.ts`` produces a top-level
         *     ``MeResponse`` type rather than aliasing the embedded
         *     auth-response shape. ``conventions.md`` "Shared schemas" requires
         *     that re-export to be a precise type, not a path-derived alias.
         */
        MeResponse: {
            /**
             * Id
             * @description UUIDv7 of the User_Account, encoded as a string.
             */
            id: string;
            /**
             * Email
             * @description Email address as submitted at registration.
             */
            email: string;
            /**
             * Display Name
             * @description Display name.
             */
            display_name: string;
            /**
             * Created At
             * Format: date-time
             * @description Registration timestamp (timezone-aware).
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last-modified timestamp (timezone-aware).
             */
            updated_at: string;
        };
        /**
         * PasswordResetConfirmRequest
         * @description Body of ``POST /api/v1/auth/password-reset/confirm`` (Requirement 5.5).
         *
         *     Fields:
         *       * ``token`` -- opaque reset token produced by the request endpoint.
         *         Validated server-side by hashing and looking up
         *         ``password_reset_tokens.token_hash``; missing / expired / used
         *         all collapse to a single ``invalid_reset_token`` envelope
         *         (Requirements 5.6, 5.7, 5.8) so the client can't distinguish.
         *       * ``new_password`` -- same 12-codepoint floor as registration
         *         (Requirement 5.9 references Requirement 1.4 + 1.5 directly).
         */
        PasswordResetConfirmRequest: {
            /**
             * Token
             * @description Opaque reset token from the issued reset link.
             */
            token: string;
            /**
             * New Password
             * @description New plaintext password; minimum 12 codepoints. Blocklist enforcement runs server-side after NFKC normalization.
             */
            new_password: string;
        };
        /**
         * PasswordResetRequestRequest
         * @description Body of ``POST /api/v1/auth/password-reset/request`` (Requirement 5.1).
         *
         *     Single field: the email address requesting a reset link. The
         *     response is always 202 with an empty body whether or not the
         *     address matches a User_Account (Requirement 5.2 -- anti-enumeration
         *     per ``security.md`` "no account enumeration").
         */
        PasswordResetRequestRequest: {
            /**
             * Email
             * Format: email
             * @description Email address to issue a reset link for.
             */
            email: string;
        };
        /**
         * RegisterRequest
         * @description Body of ``POST /api/v1/auth/register`` (Requirement 1.1).
         *
         *     Fields:
         *       * ``email`` -- :class:`pydantic.EmailStr` triggers RFC 5321 validation
         *         through ``email-validator``, which is what Requirement 1.3 requires.
         *         A syntactically valid but RFC-5321-non-compliant address (e.g. a
         *         local part longer than 64 octets) raises a Pydantic
         *         ``ValidationError`` and FastAPI maps it to 422 via the foundation
         *         RFC 7807 envelope.
         *       * ``password`` -- minimum 12 *codepoints* (Requirement 1.4). The
         *         blocklist check (Requirement 1.5) runs deeper in
         *         :class:`Password_Hasher`, not here, because §8.5 evaluates it
         *         against the post-NFKC case-folded form.
         *       * ``display_name`` -- optional. When omitted, :class:`Auth_Service`
         *         defaults it to the local part of the email (Requirement 1.7).
         *         When present, it is validated against Requirement 6.6 by
         *         :func:`_validate_display_name`.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             * @description RFC 5321-compliant email address. Stored as submitted; lookups are case-insensitive via the functional unique index.
             */
            email: string;
            /**
             * Password
             * @description Plaintext password; minimum 12 codepoints (Requirement 1.4). Blocklist enforcement runs server-side after NFKC normalization.
             */
            password: string;
            /**
             * Display Name
             * @description Optional display name. Defaults to the local part of the email when omitted. Validated per Requirement 6.6 when present.
             */
            display_name?: string | null;
        };
        /**
         * ResumeListResponse
         * @description Body of ``GET /api/v1/resumes`` (Requirement 4.1).
         *
         *     A single page of the requesting User_Account's non-deleted resumes,
         *     ordered by ``created_at`` descending, plus an opaque ``next_cursor``
         *     for cursor-based pagination per ``conventions.md`` "Pagination"
         *     (offset pagination is explicitly avoided). ``next_cursor`` is an
         *     opaque token the client echoes back via the ``cursor`` query
         *     parameter to fetch the following page; it is ``None`` when there are
         *     no further pages.
         *
         *     Each item is a :class:`ResumeResponse`, so the same field-exclusion
         *     guarantees (no ``extracted_text``, no ``storage_key``) apply to every
         *     row in the list (Requirement 4.2).
         */
        ResumeListResponse: {
            /**
             * Items
             * @description The resumes on this page, ordered by created_at descending.
             */
            items: components["schemas"]["ResumeResponse"][];
            /**
             * Next Cursor
             * @description Opaque pagination cursor for the next page, or null when this is the last page. Echo back via the ?cursor= query parameter.
             */
            next_cursor?: string | null;
        };
        /**
         * ResumeResponse
         * @description Safe Resume projection (Requirements 2.9, 4.2).
         *
         *     Carries exactly the seven fields Requirements 2.9 and 4.2 enumerate:
         *     ``id``, ``original_filename``, ``content_type``, ``byte_size``,
         *     ``extraction_status``, ``created_at``, ``updated_at``.
         *
         *     ``extracted_text`` and ``storage_key`` are intentionally absent. Both
         *     are sensitive per ``security.md``: ``extracted_text`` is Restricted
         *     PII (parsed resume content) and ``storage_key`` is the internal
         *     object-storage location. Neither may ever appear in an API response
         *     body. This exclusion is a hard security control, not a convenience --
         *     Property 17 (``tasks.md`` 10.2) asserts the response never exposes
         *     them.
         *
         *     ``original_filename`` is Restricted PII for *logging* purposes (it is
         *     never written to a log line or audit payload, per Requirement 2.6),
         *     but it is the user's own filename returned to that same user over the
         *     authenticated, non-indexed API surface for display, so it belongs in
         *     the response body (Requirements 2.9, 4.2).
         *
         *     Datetimes serialize as ISO 8601 with timezone (the database columns
         *     are ``timestamptz``); the ``conventions.md`` "ISO 8601 UTC with Z
         *     suffix" rule is honored on the wire by Pydantic's default datetime
         *     formatter when the source value is timezone-aware.
         *
         *     ``from_attributes=True`` lets the router build a response directly
         *     from the SQLAlchemy ``Resume`` row via
         *     ``ResumeResponse.model_validate(resume)``; since the ORM attribute
         *     set is a strict superset of these fields, the excluded sensitive
         *     columns are simply never read.
         */
        ResumeResponse: {
            /**
             * Id
             * @description UUIDv7 of the Resume, encoded as a string.
             */
            id: string;
            /**
             * Original Filename
             * @description Client-supplied filename, retained for display only. Never used to derive the storage key or any filesystem path.
             */
            original_filename: string;
            /**
             * Content Type
             * @description Validated media type of the uploaded file (magic-byte-detected, not the client Content-Type header).
             */
            content_type: string;
            /**
             * Byte Size
             * @description Size of the stored file in bytes.
             */
            byte_size: number;
            /**
             * Extraction Status
             * @description Text-extraction outcome: 'pending' before extraction runs, 'succeeded' when non-whitespace text was stored, 'failed' when extraction errored, timed out, or yielded only whitespace.
             * @enum {string}
             */
            extraction_status: "pending" | "succeeded" | "failed";
            /**
             * Created At
             * Format: date-time
             * @description Upload timestamp (timezone-aware).
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last-modified timestamp (timezone-aware). Bumped when extraction columns are written and on soft delete.
             */
            updated_at: string;
        };
        /**
         * ScoreBreakdownOut
         * @description The explainable breakdown behind a score (Requirement 5.5).
         *
         *     Mirrors the scorer's ``ScoreBreakdown`` dataclass and the
         *     ``match_results.score_breakdown`` JSONB shape field-for-field. The
         *     similarity and keyword-coverage components are the raw ``[0, 1]`` values
         *     before weighting, so a reader can recompute
         *     ``round(100 * (weight_similarity * similarity_component +
         *     weight_keyword * keyword_coverage_component))`` and arrive at
         *     ``final_score`` without re-running the algorithm.
         */
        ScoreBreakdownOut: {
            /**
             * Similarity Component
             * @description TF-IDF cosine similarity of resume and JD, in [0, 1].
             */
            similarity_component: number;
            /**
             * Keyword Coverage Component
             * @description Fraction of the analyzed keyword set present in the resume, in [0, 1].
             */
            keyword_coverage_component: number;
            /**
             * Weight Similarity
             * @description Weight applied to the similarity component (default 0.6).
             */
            weight_similarity: number;
            /**
             * Weight Keyword
             * @description Weight applied to the keyword-coverage component (default 0.4).
             */
            weight_keyword: number;
            /**
             * Final Score
             * @description The combined, clamped integer score in [0, 100]; equals the enclosing MatchResponse.score.
             */
            final_score: number;
            /**
             * Similarity Method
             * @description Which algorithm produced the similarity component: 'semantic-embedding' (Phase 2 pipeline) or 'tfidf' (Phase 1 engine or per-request fallback). Optional Phase 2 addition (phase-2 Requirements 3.3, 9.1, 9.5): null on pre-Phase-2 stored results, whose absence implies TF-IDF. Every Phase 1 field above keeps its name, type, and required status.
             */
            similarity_method?: string | null;
        };
        /**
         * SuggestionOut
         * @description One rule-based improvement suggestion (``{keyword, text}``).
         *
         *     Mirrors the scorer's ``Suggestion`` dataclass and the
         *     ``match_results.suggestions`` JSONB shape. ``keyword`` is the missing
         *     term the suggestion addresses (empty only for the single affirmative
         *     suggestion emitted when nothing is missing, per Requirement 7.3);
         *     ``text`` is the plain-text, user-facing guidance.
         */
        SuggestionOut: {
            /**
             * Keyword
             * @description The missing keyword this suggestion addresses; empty only for the affirmative 'already covered' suggestion.
             */
            keyword: string;
            /**
             * Text
             * @description Plain-text guidance phrased as an action for the user to take. Never fabricates experience, employers, dates, or credentials.
             */
            text: string;
        };
        /**
         * TokenPairResponse
         * @description Body of register / login / refresh on success.
         *
         *     Shape per Design §7.3 mermaid line 370 -- ``{access_token, user}``.
         *     The refresh token is **not** in the body: it rides the
         *     ``matchlayer_refresh`` HttpOnly cookie set on the same response
         *     (CSRF Strategy §9.2). The CSRF token rides a sibling
         *     ``matchlayer_csrf`` cookie. This split is what lets the access
         *     token live in a JS-readable in-memory store on the frontend
         *     (``security.md`` forbids ``localStorage`` for JWTs) while the
         *     refresh token stays out of every JS surface entirely.
         */
        TokenPairResponse: {
            /**
             * Access Token
             * @description Short-lived (15 min by default) JWT for Authorization Bearer use. Held in memory on the frontend, never persisted.
             */
            access_token: string;
            /** @description The authenticated User_Account projection. */
            user: components["schemas"]["UserResponse"];
        };
        /**
         * UserResponse
         * @description User_Account projection embedded in auth responses.
         *
         *     Carries exactly the five fields Requirements 1.7, 2.5, 3.8, and
         *     6.3 enumerate: ``id``, ``email``, ``display_name``, ``created_at``,
         *     ``updated_at``. ``password_hash``, ``failed_login_count``,
         *     ``locked_until``, and ``deleted_at`` are intentionally absent
         *     (Requirement 6.8 + ``security.md`` "Logging").
         *
         *     Datetimes serialize as ISO 8601 with timezone (the database column
         *     is ``timestamptz``); the foundation convention "ISO 8601 UTC with Z
         *     suffix" is honored on the wire by Pydantic's default datetime
         *     formatter when the source value is timezone-aware.
         *
         *     ``from_attributes=True`` lets the router build a response directly
         *     from the SQLAlchemy ``User`` row via ``UserResponse.model_validate(user)``.
         */
        UserResponse: {
            /**
             * Id
             * @description UUIDv7 of the User_Account, encoded as a string.
             */
            id: string;
            /**
             * Email
             * @description Email address as submitted at registration.
             */
            email: string;
            /**
             * Display Name
             * @description Display name. Always populated; defaults to the local part of the email when not supplied at registration.
             */
            display_name: string;
            /**
             * Created At
             * Format: date-time
             * @description Registration timestamp (timezone-aware).
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last-modified timestamp (timezone-aware). Bumped on display-name change and password change.
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Postgres is unreachable. The probe never returns DSN or credentials in the response body. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthUnhealthyResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    patch_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    password_reset_request_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_confirm_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_api_v1_resumes_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resume_api_v1_resumes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_resume_api_v1_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_v1_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_v1_matches_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_api_v1_matches__match_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_coaching_reports_api_v1_matches__match_id__coaching_reports_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachingReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_coaching_report_api_v1_matches__match_id__coaching_reports_post: {
        parameters: {
            query?: {
                /** @description When true, deliver the response as a Server-Sent Events stream (`text/event-stream`): zero or more `delta` events carrying incremental display text, then exactly one terminal event — `complete` (the validated result envelope), `degraded` (the fallback envelope), or `error` (an RFC 7807 body). Pre-stream gate rejections (401/404/422/429/503) return the same non-streaming RFC 7807 responses. When false or omitted, the documented JSON response body is returned. */
                stream?: boolean;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResultEnvelope_CoachingReport_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coaching_report_api_v1_matches__match_id__coaching_reports__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResultEnvelope_CoachingReport_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bullet_rewrites_api_v1_matches__match_id__bullet_rewrites_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulletRewriteListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bullet_rewrite_api_v1_matches__match_id__bullet_rewrites_post: {
        parameters: {
            query?: {
                /** @description When true, deliver the response as a Server-Sent Events stream (`text/event-stream`): zero or more `delta` events carrying incremental display text, then exactly one terminal event — `complete` (the validated result envelope), `degraded` (the fallback envelope), or `error` (an RFC 7807 body). Pre-stream gate rejections (401/404/422/429/503) return the same non-streaming RFC 7807 responses. When false or omitted, the documented JSON response body is returned. */
                stream?: boolean;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulletRewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResultEnvelope_BulletRewrite_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bullet_rewrite_api_v1_matches__match_id__bullet_rewrites__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResultEnvelope_BulletRewrite_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interview_question_sets_api_v1_matches__match_id__interview_question_sets_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewQuestionSetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_question_set_api_v1_matches__match_id__interview_question_sets_post: {
        parameters: {
            query?: {
                /** @description When true, deliver the response as a Server-Sent Events stream (`text/event-stream`): zero or more `delta` events carrying incremental display text, then exactly one terminal event — `complete` (the validated result envelope), `degraded` (the fallback envelope), or `error` (an RFC 7807 body). Pre-stream gate rejections (401/404/422/429/503) return the same non-streaming RFC 7807 responses. When false or omitted, the documented JSON response body is returned. */
                stream?: boolean;
            };
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResultEnvelope_InterviewQuestionSet_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_question_set_api_v1_matches__match_id__interview_question_sets__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description The requesting user's remaining LLM Daily_Quota for the current UTC day. Present on every LLM feature response, including 429 rejections; omitted only when the quota counter is unreadable. */
                    "X-LLM-Quota-Remaining"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResultEnvelope_InterviewQuestionSet_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    last_reset_link_api_v1_dev_last_reset_link_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastResetLinkResponse"];
                };
            };
        };
    };
}
