/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness/readiness probe with Postgres connectivity check.
         * @description Probe Postgres and return the canonical health envelope.
         *
         *     The handler intentionally returns :class:`fastapi.responses.JSONResponse`
         *     rather than the Pydantic model directly so the failure branch can
         *     set the 503 status code without raising an exception (which would
         *     route through the RFC 7807 catch-all in
         *     :mod:`matchlayer_api.core.errors` and produce the wrong response
         *     shape for a healthcheck).
         *
         *     Args:
         *         session: Request-scoped async SQLAlchemy session, yielded by
         *             :func:`~matchlayer_api.core.db.get_session`. Tests override
         *             this dependency via FastAPI's ``app.dependency_overrides``
         *             mapping (task 3.11).
         *
         *     Returns:
         *         :class:`JSONResponse` with status 200 and body ``{"status": "ok"}``
         *         when the ``SELECT 1`` probe succeeds; status 503 and body
         *         ``{"status": "unhealthy", "reason": "database_unreachable"}``
         *         when SQLAlchemy raises any subclass of :class:`SQLAlchemyError`.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthResponse
         * @description Body returned on the success path: ``{"status": "ok"}``.
         *
         *     Typed with :class:`typing.Literal` so the generated OpenAPI schema
         *     pins the response to that exact shape, which in turn produces a
         *     precise type when :mod:`packages/shared-types` re-exports it as
         *     ``HealthResponse`` (task 5.4).
         */
        HealthResponse: {
            /**
             * Status
             * @description Liveness signal. Always the literal string 'ok' on a 200 response.
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * HealthUnhealthyResponse
         * @description Body returned on the failure path.
         *
         *     Surfaced in the OpenAPI ``responses`` map for ``503`` so the
         *     contract is explicit: the response carries a short symbolic
         *     ``reason`` token and never a DSN, credentials, or any PII.
         */
        HealthUnhealthyResponse: {
            /**
             * Status
             * @description Liveness signal. Always the literal string 'unhealthy' on a 503 response.
             * @default unhealthy
             * @constant
             */
            status: "unhealthy";
            /**
             * Reason
             * @description Symbolic, machine-readable failure code. Phase 6 load balancers and alerting branch on this token; it never contains DSN, credentials, or PII.
             * @constant
             */
            reason: "database_unreachable";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Postgres is unreachable. The probe never returns DSN or credentials in the response body. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthUnhealthyResponse"];
                };
            };
        };
    };
}
