"""llm_results and llm_invocation_logs tables

Revision ID: 0004_llm_tables
Revises: 0003_pgvector_embeddings
Create Date: 2026-06-24

Creates the two Phase 3 LLM-layer tables for ``phase-3-llm-layer``:

* ``llm_results`` — one persisted, schema-validated LLM_Feature output
  per row (Requirement 16.3).
* ``llm_invocation_logs`` — exactly one append-only row per
  LLM_Provider call, success or failure (Requirements 12.1-12.4).

No soft delete (deliberate)
---------------------------
Neither table carries ``deleted_at``. ``conventions.md`` scopes soft
delete to *user-facing entities*; invocation logs are append-only
operational records that Phase 3 must never delete, expire, or
overwrite (Requirement 12.4), and ``llm_results`` rows are derived
artifacts that cascade with their owning match — the match itself is
the soft-deleted user-facing entity.

Nullable token/cost columns (Requirement 12.2)
----------------------------------------------
``input_tokens``, ``output_tokens``, and ``cost_usd`` are nullable:
NULL means "unavailable from the provider", which must stay
distinguishable from a recorded value of zero. ``cost_basis``
(NOT NULL) records how cost was resolved: ``provider_reported`` |
``computed`` | ``unavailable``. ``cost_usd`` is ``NUMERIC(10, 6)`` —
exact decimal arithmetic for the Spend_Circuit_Breaker's monthly SUM
(Requirement 14.1); micro-dollar precision covers per-call costs of
the configured models.

Output XOR failure (Requirements 12.1, 8.3)
-------------------------------------------
``output`` (JSONB, validated structured output) is NULL on failure;
``failure_category`` (a FailureReason enum value) is NULL on success.
Both are plain nullable columns — the XOR is enforced by the single
writer (``services/llm/invocation_log.py``), not a CHECK constraint,
so a future failure taxonomy change needs no migration.

Index justifications (conventions.md — every WHERE/ORDER BY on a
non-PK column gets an index, documented here)
-------------------------------------------------------------------
* ``llm_results_match_feature_created_idx``
  ``(match_result_id, feature, created_at DESC)`` — serves both hot
  read paths: the newest-first cursor-paginated list endpoints
  (``WHERE match_result_id = ? AND feature = ? ORDER BY created_at
  DESC``, Requirement 16.4) and the Resume_Coach persisted-result
  reuse lookup (newest row for a match+feature, Requirement 5.4).
  ``created_at DESC`` matches the scan direction so no sort node is
  needed.
* ``llm_invocation_logs_replay_idx``
  ``(feature, prompt_template_version, llm_model, created_at)`` —
  Phase 5 evaluation replay selects comparable invocation sets by
  feature, prompt version, and model over a time range
  (Requirement 12.4); ``created_at`` last makes the time-range
  predicate a range scan within each group.
* ``llm_invocation_logs_created_at_idx`` ``(created_at)`` — the
  Spend_Circuit_Breaker sums ``cost_usd`` over the current UTC
  calendar month on every evaluation (Requirement 14.1); a bare
  ``created_at`` index turns that into a range scan instead of a
  monthly full-table scan on an ever-growing append-only table.

Foreign-key deletion semantics
------------------------------
``llm_results`` FKs are ``ON DELETE CASCADE`` (both ``users`` and
``match_results``): results are derived artifacts that must not
outlive their source. ``llm_invocation_logs`` FKs deliberately carry
NO cascade (Postgres default ``NO ACTION``): the logs are append-only
records (Requirement 12.4) and a parent hard-delete must not silently
destroy them — Phase 3 has no hard-delete path for users or matches
(soft delete via ``deleted_at``), so the restrictive FK acts as a
guard, and any future purge feature must handle logs explicitly.

PK defaults: as in every prior revision, UUIDv7 primary keys are
generated by the ORM (``uuid_utils``), not by a server default — no
DDL default is declared.

Atomicity: Postgres DDL is transactional and Alembic runs this
revision in one transaction; any failure rolls back the whole
revision leaving no partial objects, so a failed run is safely
re-runnable.

No fine-grained GRANT/REVOKE block is needed: ``0001``'s
``ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT,
UPDATE, DELETE ON TABLES TO matchlayer_app`` covers both new tables.

Design reference: Data Models / New tables (phase-3-llm-layer);
Requirements 12.1, 12.3, 12.4, 16.3.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_llm_tables"
down_revision: str | Sequence[str] | None = "0003_pgvector_embeddings"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. llm_results — one validated LLM_Feature output per row (16.3).
    op.create_table(
        "llm_results",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "match_result_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("match_results.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # 'resume_coach' | 'bullet_rewrite' | 'interview_questions'
        sa.Column("feature", sa.Text(), nullable=False),
        sa.Column("prompt_template_version", sa.Integer(), nullable=False),
        sa.Column("llm_model", sa.Text(), nullable=False),
        # Validated CoachingReport / BulletRewrite / InterviewQuestionSet.
        sa.Column("payload", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )

    # 2. llm_invocation_logs — one append-only row per provider call (12.1).
    #    FKs carry no cascade: see the docstring's deletion-semantics note.
    op.create_table(
        "llm_invocation_logs",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column(
            "match_result_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("match_results.id"),
            nullable=False,
        ),
        sa.Column("feature", sa.Text(), nullable=False),
        sa.Column("prompt_template_version", sa.Integer(), nullable=False),
        sa.Column("llm_model", sa.Text(), nullable=False),
        sa.Column("redactor_version", sa.Text(), nullable=False),
        # sha256 over the redacted prompt input — never the raw input
        # (12.3); same digest as the LLM_Cache key (12.6).
        sa.Column("input_hash", sa.Text(), nullable=False),
        # Validated structured output; NULL on failure (12.1).
        sa.Column("output", sa.dialects.postgresql.JSONB(), nullable=True),
        # FailureReason enum value; NULL on success (12.1).
        sa.Column("failure_category", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        # NULL = unavailable, distinct from a recorded 0 (12.2).
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(10, 6), nullable=True),
        # 'provider_reported' | 'computed' | 'unavailable' (12.2).
        sa.Column("cost_basis", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )

    # 3. Indexes — justifications in the docstring above (conventions.md).
    op.create_index(
        "llm_results_match_feature_created_idx",
        "llm_results",
        ["match_result_id", "feature", sa.text("created_at DESC")],
    )
    op.create_index(
        "llm_invocation_logs_replay_idx",
        "llm_invocation_logs",
        ["feature", "prompt_template_version", "llm_model", "created_at"],
    )
    op.create_index(
        "llm_invocation_logs_created_at_idx",
        "llm_invocation_logs",
        ["created_at"],
    )


def downgrade() -> None:
    # Drop in reverse creation order.
    op.drop_index("llm_invocation_logs_created_at_idx", table_name="llm_invocation_logs")
    op.drop_index("llm_invocation_logs_replay_idx", table_name="llm_invocation_logs")
    op.drop_table("llm_invocation_logs")

    op.drop_index("llm_results_match_feature_created_idx", table_name="llm_results")
    op.drop_table("llm_results")
