"""agent_jobs and agent_runs tables

Revision ID: 0005_agent_tables
Revises: 0004_llm_tables
Create Date: 2026-07-08

Creates the two Phase 4 agent-persistence tables for ``phase-4-agentic``:

* ``agent_jobs`` — one asynchronous analysis job per row (Job_Status
  lifecycle ``queued → running → completed | failed``, Requirement 12.1).
* ``agent_runs`` — exactly one immutable row per Agent node invocation
  (Requirements 12.2, 12.6).

Status CHECK constraints
------------------------
``agent_jobs.status`` is constrained to exactly the four Job_Status
values (``queued``, ``running``, ``completed``, ``failed``) and
``agent_runs.status`` to exactly the three invocation statuses
(``completed``, ``degraded``, ``failed``) — Requirement 12.1 says each
column holds "exactly one" of those values, so the database enforces
the closed set rather than trusting every writer.

Nullable lifecycle/result columns
---------------------------------
``started_at`` and ``completed_at`` are nullable ``timestamptz``: NULL
means "this lifecycle point has not been reached", set by the worker on
the ``running`` and terminal transitions (Requirement 11.4).
``result_json`` is set iff the job completed; ``error_json`` (structured,
PII-free) is null unless the job failed (Requirement 12.1). The XOR is
enforced by the single writer (``services/agent_jobs/service.py``'s
guarded state machine), not a CHECK constraint, so a future status
taxonomy change needs no migration — same posture as ``0004``'s
output-XOR-failure columns. ``agent_runs.failure_reason_json`` is null
iff status is ``completed`` (Requirement 12.1), enforced the same way.

No soft delete (deliberate)
---------------------------
Neither table carries ``deleted_at``. ``conventions.md`` scopes soft
delete to *user-facing entities*; jobs and runs are operational records
retained for Phase 5 evaluation consumption — no Phase 4 code path
deletes them, and ``agent_runs`` rows are immutable once written
(Requirement 12.6).

Index justifications (conventions.md — every WHERE/ORDER BY on a
non-PK column gets an index, documented here)
-------------------------------------------------------------------
* ``agent_jobs_user_id_idx`` ``(user_id)`` — every owner-scoped job
  read filters by ``user_id`` (ownership indistinguishability lookups
  for ``GET /api/v1/jobs/{id}``, Requirements 10.4, 12.4).
* ``agent_jobs_match_user_status_idx`` ``(match_id, user_id, status)``
  — the analyze endpoint's in-flight idempotency lookup ("does a
  non-terminal job already exist for this (match, user)?") filters on
  all three columns (Requirement 10.5, design decision D5).
* ``agent_jobs_match_user_inflight_uniq`` — **partial unique** index on
  ``(match_id, user_id) WHERE status IN ('queued', 'running')``: the
  database-level guarantee that at most one non-terminal Agent_Job
  exists per (Match_Result, User_Account) pair even under concurrent
  analyze requests (Requirement 10.5, D5). Application-level
  check-then-insert races; a unique-violation on insert is caught and
  resolved to the existing job. Terminal rows (``completed``/``failed``)
  fall outside the predicate, so a fresh job can always be created
  after the prior one terminates.
* ``agent_runs_job_id_idx`` ``(job_id)`` — the job status endpoint
  derives per-agent step statuses by selecting all runs for one job
  (Requirements 10.2, 12.1), and the worker appends runs keyed by the
  same FK.

Foreign-key deletion semantics
------------------------------
All FKs deliberately carry NO cascade (Postgres default ``NO ACTION``),
mirroring ``0004``'s ``llm_invocation_logs``: jobs and runs are retained
operational records (Requirement 12.6) and a parent hard-delete must not
silently destroy them — Phase 4 has no hard-delete path for users,
matches, jobs, or runs (user-facing entities soft-delete via
``deleted_at``), so the restrictive FK acts as a guard and any future
purge feature must handle these tables explicitly.

PK defaults: as in every prior revision, UUIDv7 primary keys are
generated by the ORM (``uuid_utils``), not by a server default — no DDL
default is declared. ``attempts`` carries a DB-level ``0`` default
(matching ``0001``'s ``failed_login_count``) so a raw insert can never
produce a NULL redelivery counter (Requirement 11.5).

Atomicity: Postgres DDL is transactional and Alembic runs this revision
in one transaction; any failure rolls back the whole revision leaving no
partial objects, so a failed run is safely re-runnable.

No fine-grained GRANT/REVOKE block is needed: ``0001``'s
``ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT,
UPDATE, DELETE ON TABLES TO matchlayer_app`` covers both new tables.

Design reference: Data Models / ``agent_jobs`` and ``agent_runs``
(phase-4-agentic); Requirements 12.1, 10.5.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005_agent_tables"
down_revision: str | Sequence[str] | None = "0004_llm_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. agent_jobs — one async analysis job per row (Requirement 12.1).
    #    FKs carry no cascade: see the docstring's deletion-semantics note.
    op.create_table(
        "agent_jobs",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column(
            "match_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("match_results.id"),
            nullable=False,
        ),
        # Job_Status — exactly one of the four lifecycle values.
        sa.Column("status", sa.Text(), nullable=False),
        # SQS redelivery counter (Requirement 11.5).
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        # NULL until the worker records the corresponding transition (11.4).
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        # AnalysisResult; set iff status = completed.
        sa.Column("result_json", sa.dialects.postgresql.JSONB(), nullable=True),
        # Structured PII-free error; null unless status = failed.
        sa.Column("error_json", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed')",
            name="agent_jobs_status_check",
        ),
    )

    # 2. agent_runs — one immutable row per Agent invocation (12.2, 12.6).
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "job_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("agent_jobs.id"),
            nullable=False,
        ),
        # One of the five node names (resume_analysis, ats, skill_gap,
        # improvement, synthesizer).
        sa.Column("agent_name", sa.Text(), nullable=False),
        # Redacted/derived content only — never raw resume text (12.3).
        sa.Column("input_state_json", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("output_state_json", sa.dialects.postgresql.JSONB(), nullable=False),
        # Node-invocation-start → output-return (same boundary as the
        # per-node timeout, Requirement 12.2).
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        # Structured failure reason; null iff status = completed (12.1).
        sa.Column("failure_reason_json", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'degraded', 'failed')",
            name="agent_runs_status_check",
        ),
    )

    # 3. Indexes — justifications in the docstring above (conventions.md).
    op.create_index("agent_jobs_user_id_idx", "agent_jobs", ["user_id"])
    op.create_index(
        "agent_jobs_match_user_status_idx",
        "agent_jobs",
        ["match_id", "user_id", "status"],
    )
    # Partial unique index — the in-flight idempotency guarantee (10.5, D5).
    op.create_index(
        "agent_jobs_match_user_inflight_uniq",
        "agent_jobs",
        ["match_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index("agent_runs_job_id_idx", "agent_runs", ["job_id"])


def downgrade() -> None:
    # Drop in reverse creation order; agent_runs first (FK to agent_jobs).
    op.drop_index("agent_runs_job_id_idx", table_name="agent_runs")
    op.drop_table("agent_runs")

    op.drop_index("agent_jobs_match_user_inflight_uniq", table_name="agent_jobs")
    op.drop_index("agent_jobs_match_user_status_idx", table_name="agent_jobs")
    op.drop_index("agent_jobs_user_id_idx", table_name="agent_jobs")
    op.drop_table("agent_jobs")
