"""Skill_Lexicon loader and Scorer_Version (phase-1-matching, task 3.2).

The ``Skill_Lexicon`` is the committed, versioned vocabulary the deterministic
non-LLM ``Match_Scorer`` matches against. This module loads the package-data
artifact shipped under ``matchlayer_api.scoring.data`` via
:mod:`importlib.resources` (stdlib only — Requirement 10.1's import boundary:
``scoring/`` imports only scikit-learn and the standard library) and exposes:

* the canonical skill terms,
* alias normalization (surface forms → canonical),
* per-term weight / metadata lookup, and
* the artifact's ``lexicon_version``.

It also defines :data:`ALGORITHM_VERSION` and computes the **Scorer_Version**
``f"{ALGORITHM_VERSION}+lex.{lexicon_version}"`` (Requirement 10.4). The lexicon
version flows into the Scorer_Version so that changing the lexicon changes the
``scorer_version`` persisted on subsequently created Match_Results, keeping a
stored score reproducible and auditable.

Source of truth vs runtime artifact (Requirement 10.3, ``structure.md``): the
canonical source lives under ``ml/lexicon/skill_lexicon.v1.json`` and is
regenerated by ``ml/pipelines/build_skill_lexicon.py`` — **never imported by
the API at runtime**. This module reads only the committed copy that ships as
package data; a CI drift check keeps the two byte-identical.

Design reference: "Skill_Lexicon" and "Source of truth vs runtime artifact".
Requirements covered: 10.3, 10.4.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from typing import Any, Final

# ---------------------------------------------------------------------------
# Versioning
# ---------------------------------------------------------------------------

# The Match_Scorer *algorithm* version. Bump this when the scoring algorithm
# itself changes in a way that alters produced scores (new components, changed
# normalization, changed weighting math) — independent of the lexicon content.
# It combines with the lexicon version into the Scorer_Version (Requirement
# 10.4) so a persisted score is attributable to the exact algorithm + lexicon
# that produced it.
ALGORITHM_VERSION: Final[str] = "1.0.0"

# The artifact JSON *shape* this loader understands. Distinct from the lexicon
# *content* version carried inside the artifact. Bump in lockstep with the
# build pipeline's ``SCHEMA_VERSION`` whenever the artifact layout changes.
SUPPORTED_SCHEMA_VERSION: Final[int] = 1

# Where the committed runtime artifact lives, as an importable package + name.
# Resolved through importlib.resources so it works from a built wheel too.
_ARTIFACT_PACKAGE: Final[str] = "matchlayer_api.scoring.data"
_ARTIFACT_NAME: Final[str] = "skill_lexicon.v1.json"


def scorer_version(lexicon_version: str) -> str:
    """Compose the Scorer_Version from the algorithm and lexicon versions.

    ``f"{ALGORITHM_VERSION}+lex.{lexicon_version}"`` (Requirement 10.4). Exposed
    as a free function so the formula has a single home shared by
    :attr:`Skill_Lexicon.scorer_version` and any caller that only has a version
    string in hand.
    """
    return f"{ALGORITHM_VERSION}+lex.{lexicon_version}"


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class LexiconError(ValueError):
    """The committed lexicon artifact is missing required keys or malformed.

    A subclass of :class:`ValueError` because a broken artifact is a
    programming/packaging error surfaced at load time, not a user input fault.
    """


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class SkillEntry:
    """One canonical skill and its metadata (a row of the artifact's ``skills``).

    ``canonical`` and ``aliases`` are stored lower-cased exactly as the artifact
    ships them, so lookups against normalized input compare directly.
    """

    canonical: str
    display: str
    category: str
    weight: float
    aliases: tuple[str, ...]


def _normalize_term(term: str) -> str:
    """Case-fold and collapse internal whitespace to a single space.

    Shared by artifact loading and runtime lookups so an alias such as
    ``"machine  learning"`` and the input ``"Machine Learning"`` resolve to the
    same key. Multi-word aliases in the artifact (e.g. ``"dot net"``) rely on
    this whitespace collapsing.
    """
    return " ".join(term.casefold().split())


class Skill_Lexicon:  # noqa: N801 -- design uses the underscored component name.
    """Read-only view over the committed Skill_Lexicon artifact.

    Construct from a parsed artifact document (a mapping with the keys
    ``schema_version``, ``lexicon_version`` and ``skills``) or, more commonly,
    via :func:`load_lexicon`, which reads the shipped package data. Instances
    are immutable after construction and safe to share.
    """

    def __init__(self, document: dict[str, Any]) -> None:
        self._lexicon_version: str = _require_str(document, "lexicon_version")

        schema_version = _require_int(document, "schema_version")
        if schema_version != SUPPORTED_SCHEMA_VERSION:
            raise LexiconError(
                f"unsupported lexicon schema_version {schema_version!r}; "
                f"this loader understands {SUPPORTED_SCHEMA_VERSION!r}"
            )

        raw_skills = document.get("skills")
        if not isinstance(raw_skills, list):
            raise LexiconError("artifact key 'skills' must be a list")

        entries: dict[str, SkillEntry] = {}
        alias_to_canonical: dict[str, str] = {}
        canonical_terms: list[str] = []

        for raw in raw_skills:
            if not isinstance(raw, dict):
                raise LexiconError("each entry in 'skills' must be an object")
            entry = _parse_skill(raw)
            if entry.canonical in entries:
                raise LexiconError(f"duplicate canonical term: {entry.canonical!r}")
            entries[entry.canonical] = entry
            canonical_terms.append(entry.canonical)
            for alias in entry.aliases:
                # The build pipeline already guarantees aliases are unique and
                # do not collide with canonicals; last-writer-wins here is a
                # defensive no-op rather than a contract.
                alias_to_canonical[alias] = entry.canonical

        self._entries: Final[dict[str, SkillEntry]] = entries
        self._alias_to_canonical: Final[dict[str, str]] = alias_to_canonical
        self._canonical_terms: Final[tuple[str, ...]] = tuple(canonical_terms)

    # -- Versioning --------------------------------------------------------

    @property
    def lexicon_version(self) -> str:
        """The artifact's content version (e.g. ``"1.0.0"``)."""
        return self._lexicon_version

    @property
    def scorer_version(self) -> str:
        """``f"{ALGORITHM_VERSION}+lex.{lexicon_version}"`` (Requirement 10.4)."""
        return scorer_version(self._lexicon_version)

    # -- Canonical terms ---------------------------------------------------

    @property
    def canonical_terms(self) -> tuple[str, ...]:
        """All canonical skill terms, in the artifact's (sorted) order."""
        return self._canonical_terms

    @property
    def entries(self) -> tuple[SkillEntry, ...]:
        """Every :class:`SkillEntry`, in canonical-term order."""
        return tuple(self._entries[term] for term in self._canonical_terms)

    def is_canonical(self, term: str) -> bool:
        """True if ``term`` (after normalization) is a canonical skill term."""
        return _normalize_term(term) in self._entries

    # -- Alias normalization ----------------------------------------------

    def normalize(self, term: str) -> str:
        """Resolve ``term`` to its canonical form.

        Case-folds and collapses whitespace, then maps a known alias to its
        canonical term. A term that is neither a known alias nor a canonical
        skill is returned in its normalized (case-folded, whitespace-collapsed)
        form unchanged — callers such as the Keyword_Analyzer also feed
        free-text TF-IDF terms through here, which must pass through cleanly.
        """
        normalized = _normalize_term(term)
        if normalized in self._entries:
            return normalized
        return self._alias_to_canonical.get(normalized, normalized)

    # -- Per-term metadata / weight lookup --------------------------------

    def entry(self, term: str) -> SkillEntry | None:
        """The :class:`SkillEntry` for ``term`` (canonical or alias), else ``None``."""
        return self._entries.get(self.normalize(term))

    def weight(self, term: str) -> float | None:
        """The weight for ``term`` (canonical or alias), or ``None`` if unknown."""
        entry = self.entry(term)
        return entry.weight if entry is not None else None


# ---------------------------------------------------------------------------
# Parsing helpers (typed extraction from the parsed JSON document)
# ---------------------------------------------------------------------------


def _require_str(document: dict[str, Any], key: str) -> str:
    value = document.get(key)
    if not isinstance(value, str):
        raise LexiconError(f"artifact key {key!r} must be a string")
    return value


def _require_int(document: dict[str, Any], key: str) -> int:
    value = document.get(key)
    # ``bool`` is an ``int`` subclass; reject it so a stray ``true`` is caught.
    if not isinstance(value, int) or isinstance(value, bool):
        raise LexiconError(f"artifact key {key!r} must be an integer")
    return value


def _parse_skill(raw: dict[str, Any]) -> SkillEntry:
    canonical = raw.get("canonical")
    display = raw.get("display")
    category = raw.get("category")
    weight = raw.get("weight")
    aliases = raw.get("aliases", [])

    if not isinstance(canonical, str) or not canonical:
        raise LexiconError("skill 'canonical' must be a non-empty string")
    if not isinstance(display, str):
        raise LexiconError(f"skill {canonical!r} 'display' must be a string")
    if not isinstance(category, str):
        raise LexiconError(f"skill {canonical!r} 'category' must be a string")
    # ``bool`` is an ``int`` (hence a valid number to isinstance); exclude it.
    if not isinstance(weight, (int, float)) or isinstance(weight, bool):
        raise LexiconError(f"skill {canonical!r} 'weight' must be a number")
    if not isinstance(aliases, list) or not all(isinstance(a, str) for a in aliases):
        raise LexiconError(f"skill {canonical!r} 'aliases' must be a list of strings")

    return SkillEntry(
        canonical=_normalize_term(canonical),
        display=display,
        category=category,
        weight=float(weight),
        aliases=tuple(_normalize_term(a) for a in aliases),
    )


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _read_artifact_text() -> str:
    """Read the committed lexicon artifact's bytes via importlib.resources."""
    resource = resources.files(_ARTIFACT_PACKAGE).joinpath(_ARTIFACT_NAME)
    return resource.read_text(encoding="utf-8")


@lru_cache(maxsize=1)
def load_lexicon() -> Skill_Lexicon:
    """Load and cache the committed Skill_Lexicon shipped as package data.

    Cached: the artifact is immutable for the life of the process, and the
    ``ml/`` scorer adapter builds a single scorer from it. Tests that need a
    distinct instance construct :class:`Skill_Lexicon` directly.
    """
    raw: Any = json.loads(_read_artifact_text())
    if not isinstance(raw, dict):
        raise LexiconError("lexicon artifact must be a JSON object")
    return Skill_Lexicon(raw)
